spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      authorizationserver:
        issuer-url: ${ISSUER_URL}

logging:
  level:
    com.auth.server: INFO
    org.springframework.security: WARN
